// Declaración de variables
let contenedorLoginRegistro = document.querySelector(".contenedorLoginRegistro");
let formularioLogin = document.querySelector(".formularioLogin");
let formularioRegistro = document.querySelector(".formularioRegistro");
let cajaLogin = document.querySelector(".cajaLogin");
let cajaRegistro = document.querySelector(".cajaRegistro");
let btnIniciarSesion = document.getElementById("btnIniciarSesion");
let botonGuardar = document.getElementById("btnGuardar");
let botonIngresar = document.getElementById("btnIngresar");
